---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maple.
--- DateTime: 2023/9/27 10:13
---

local del = "seckill:order:"
for i = 1, 1000 do
    if (redis.call("exists", del .. i) == 1) then
        redis.call("del", del .. i)
    end
end



